"""autogenerated by genpy from raptor/TrainDeepFeatureModelRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg
import sensor_msgs.msg

class TrainDeepFeatureModelRequest(genpy.Message):
  _md5sum = "4c09d956a60c3c731783e904d8b670a6"
  _type = "raptor/TrainDeepFeatureModelRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """sensor_msgs/Image msg0
sensor_msgs/Image msg1
sensor_msgs/Image msg2
sensor_msgs/Image msg3
sensor_msgs/Image msg4
int32 numOfObjects
string objLabel

================================================================================
MSG: sensor_msgs/Image
# This message contains an uncompressed image
# (0, 0) is at top-left corner of image
#

Header header        # Header timestamp should be acquisition time of image
                     # Header frame_id should be optical frame of camera
                     # origin of frame should be optical center of cameara
                     # +x should point to the right in the image
                     # +y should point down in the image
                     # +z should point into to plane of the image
                     # If the frame_id here and the frame_id of the CameraInfo
                     # message associated with the image conflict
                     # the behavior is undefined

uint32 height         # image height, that is, number of rows
uint32 width          # image width, that is, number of columns

# The legal values for encoding are in file src/image_encodings.cpp
# If you want to standardize a new string format, join
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.

string encoding       # Encoding of pixels -- channel meaning, ordering, size
                      # taken from the list of strings in src/image_encodings.cpp

uint8 is_bigendian    # is this data bigendian?
uint32 step           # Full row length in bytes
uint8[] data          # actual matrix data, size is (step * rows)

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['msg0','msg1','msg2','msg3','msg4','numOfObjects','objLabel']
  _slot_types = ['sensor_msgs/Image','sensor_msgs/Image','sensor_msgs/Image','sensor_msgs/Image','sensor_msgs/Image','int32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       msg0,msg1,msg2,msg3,msg4,numOfObjects,objLabel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrainDeepFeatureModelRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.msg0 is None:
        self.msg0 = sensor_msgs.msg.Image()
      if self.msg1 is None:
        self.msg1 = sensor_msgs.msg.Image()
      if self.msg2 is None:
        self.msg2 = sensor_msgs.msg.Image()
      if self.msg3 is None:
        self.msg3 = sensor_msgs.msg.Image()
      if self.msg4 is None:
        self.msg4 = sensor_msgs.msg.Image()
      if self.numOfObjects is None:
        self.numOfObjects = 0
      if self.objLabel is None:
        self.objLabel = ''
    else:
      self.msg0 = sensor_msgs.msg.Image()
      self.msg1 = sensor_msgs.msg.Image()
      self.msg2 = sensor_msgs.msg.Image()
      self.msg3 = sensor_msgs.msg.Image()
      self.msg4 = sensor_msgs.msg.Image()
      self.numOfObjects = 0
      self.objLabel = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.msg0.header.seq, _x.msg0.header.stamp.secs, _x.msg0.header.stamp.nsecs))
      _x = self.msg0.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg0.height, _x.msg0.width))
      _x = self.msg0.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg0.is_bigendian, _x.msg0.step))
      _x = self.msg0.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.msg1.header.seq, _x.msg1.header.stamp.secs, _x.msg1.header.stamp.nsecs))
      _x = self.msg1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg1.height, _x.msg1.width))
      _x = self.msg1.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg1.is_bigendian, _x.msg1.step))
      _x = self.msg1.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.msg2.header.seq, _x.msg2.header.stamp.secs, _x.msg2.header.stamp.nsecs))
      _x = self.msg2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg2.height, _x.msg2.width))
      _x = self.msg2.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg2.is_bigendian, _x.msg2.step))
      _x = self.msg2.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.msg3.header.seq, _x.msg3.header.stamp.secs, _x.msg3.header.stamp.nsecs))
      _x = self.msg3.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg3.height, _x.msg3.width))
      _x = self.msg3.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg3.is_bigendian, _x.msg3.step))
      _x = self.msg3.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.msg4.header.seq, _x.msg4.header.stamp.secs, _x.msg4.header.stamp.nsecs))
      _x = self.msg4.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg4.height, _x.msg4.width))
      _x = self.msg4.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg4.is_bigendian, _x.msg4.step))
      _x = self.msg4.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_i.pack(self.numOfObjects))
      _x = self.objLabel
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.msg0 is None:
        self.msg0 = sensor_msgs.msg.Image()
      if self.msg1 is None:
        self.msg1 = sensor_msgs.msg.Image()
      if self.msg2 is None:
        self.msg2 = sensor_msgs.msg.Image()
      if self.msg3 is None:
        self.msg3 = sensor_msgs.msg.Image()
      if self.msg4 is None:
        self.msg4 = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.msg0.header.seq, _x.msg0.header.stamp.secs, _x.msg0.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg0.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg0.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg0.height, _x.msg0.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg0.encoding = str[start:end].decode('utf-8')
      else:
        self.msg0.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg0.is_bigendian, _x.msg0.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg0.data = str[start:end].decode('utf-8')
      else:
        self.msg0.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg1.header.seq, _x.msg1.header.stamp.secs, _x.msg1.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg1.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg1.height, _x.msg1.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg1.encoding = str[start:end].decode('utf-8')
      else:
        self.msg1.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg1.is_bigendian, _x.msg1.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg1.data = str[start:end].decode('utf-8')
      else:
        self.msg1.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg2.header.seq, _x.msg2.header.stamp.secs, _x.msg2.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg2.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg2.height, _x.msg2.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg2.encoding = str[start:end].decode('utf-8')
      else:
        self.msg2.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg2.is_bigendian, _x.msg2.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg2.data = str[start:end].decode('utf-8')
      else:
        self.msg2.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg3.header.seq, _x.msg3.header.stamp.secs, _x.msg3.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg3.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg3.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg3.height, _x.msg3.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg3.encoding = str[start:end].decode('utf-8')
      else:
        self.msg3.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg3.is_bigendian, _x.msg3.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg3.data = str[start:end].decode('utf-8')
      else:
        self.msg3.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg4.header.seq, _x.msg4.header.stamp.secs, _x.msg4.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg4.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg4.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg4.height, _x.msg4.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg4.encoding = str[start:end].decode('utf-8')
      else:
        self.msg4.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg4.is_bigendian, _x.msg4.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg4.data = str[start:end].decode('utf-8')
      else:
        self.msg4.data = str[start:end]
      start = end
      end += 4
      (self.numOfObjects,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.objLabel = str[start:end].decode('utf-8')
      else:
        self.objLabel = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.msg0.header.seq, _x.msg0.header.stamp.secs, _x.msg0.header.stamp.nsecs))
      _x = self.msg0.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg0.height, _x.msg0.width))
      _x = self.msg0.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg0.is_bigendian, _x.msg0.step))
      _x = self.msg0.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.msg1.header.seq, _x.msg1.header.stamp.secs, _x.msg1.header.stamp.nsecs))
      _x = self.msg1.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg1.height, _x.msg1.width))
      _x = self.msg1.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg1.is_bigendian, _x.msg1.step))
      _x = self.msg1.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.msg2.header.seq, _x.msg2.header.stamp.secs, _x.msg2.header.stamp.nsecs))
      _x = self.msg2.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg2.height, _x.msg2.width))
      _x = self.msg2.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg2.is_bigendian, _x.msg2.step))
      _x = self.msg2.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.msg3.header.seq, _x.msg3.header.stamp.secs, _x.msg3.header.stamp.nsecs))
      _x = self.msg3.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg3.height, _x.msg3.width))
      _x = self.msg3.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg3.is_bigendian, _x.msg3.step))
      _x = self.msg3.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.msg4.header.seq, _x.msg4.header.stamp.secs, _x.msg4.header.stamp.nsecs))
      _x = self.msg4.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.msg4.height, _x.msg4.width))
      _x = self.msg4.encoding
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_BI.pack(_x.msg4.is_bigendian, _x.msg4.step))
      _x = self.msg4.data
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_struct_i.pack(self.numOfObjects))
      _x = self.objLabel
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.msg0 is None:
        self.msg0 = sensor_msgs.msg.Image()
      if self.msg1 is None:
        self.msg1 = sensor_msgs.msg.Image()
      if self.msg2 is None:
        self.msg2 = sensor_msgs.msg.Image()
      if self.msg3 is None:
        self.msg3 = sensor_msgs.msg.Image()
      if self.msg4 is None:
        self.msg4 = sensor_msgs.msg.Image()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.msg0.header.seq, _x.msg0.header.stamp.secs, _x.msg0.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg0.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg0.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg0.height, _x.msg0.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg0.encoding = str[start:end].decode('utf-8')
      else:
        self.msg0.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg0.is_bigendian, _x.msg0.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg0.data = str[start:end].decode('utf-8')
      else:
        self.msg0.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg1.header.seq, _x.msg1.header.stamp.secs, _x.msg1.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg1.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg1.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg1.height, _x.msg1.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg1.encoding = str[start:end].decode('utf-8')
      else:
        self.msg1.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg1.is_bigendian, _x.msg1.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg1.data = str[start:end].decode('utf-8')
      else:
        self.msg1.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg2.header.seq, _x.msg2.header.stamp.secs, _x.msg2.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg2.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg2.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg2.height, _x.msg2.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg2.encoding = str[start:end].decode('utf-8')
      else:
        self.msg2.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg2.is_bigendian, _x.msg2.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg2.data = str[start:end].decode('utf-8')
      else:
        self.msg2.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg3.header.seq, _x.msg3.header.stamp.secs, _x.msg3.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg3.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg3.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg3.height, _x.msg3.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg3.encoding = str[start:end].decode('utf-8')
      else:
        self.msg3.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg3.is_bigendian, _x.msg3.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg3.data = str[start:end].decode('utf-8')
      else:
        self.msg3.data = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.msg4.header.seq, _x.msg4.header.stamp.secs, _x.msg4.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg4.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.msg4.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg4.height, _x.msg4.width,) = _struct_2I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg4.encoding = str[start:end].decode('utf-8')
      else:
        self.msg4.encoding = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.msg4.is_bigendian, _x.msg4.step,) = _struct_BI.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.msg4.data = str[start:end].decode('utf-8')
      else:
        self.msg4.data = str[start:end]
      start = end
      end += 4
      (self.numOfObjects,) = _struct_i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.objLabel = str[start:end].decode('utf-8')
      else:
        self.objLabel = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
_struct_3I = struct.Struct("<3I")
_struct_2I = struct.Struct("<2I")
_struct_BI = struct.Struct("<BI")
"""autogenerated by genpy from raptor/TrainDeepFeatureModelResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class TrainDeepFeatureModelResponse(genpy.Message):
  _md5sum = "735d5bb657ca4356bf24ff5eb86bf466"
  _type = "raptor/TrainDeepFeatureModelResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32[] result


"""
  __slots__ = ['result']
  _slot_types = ['int32[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       result

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TrainDeepFeatureModelResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.result is None:
        self.result = []
    else:
      self.result = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.result)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(struct.pack(pattern, *self.result))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.result = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.result)
      buff.write(_struct_I.pack(length))
      pattern = '<%si'%length
      buff.write(self.result.tostring())
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%si'%length
      start = end
      end += struct.calcsize(pattern)
      self.result = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
class TrainDeepFeatureModel(object):
  _type          = 'raptor/TrainDeepFeatureModel'
  _md5sum = '5eb9f87fdb267df0c81d5649a9e37ab9'
  _request_class  = TrainDeepFeatureModelRequest
  _response_class = TrainDeepFeatureModelResponse
